# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [6]:
import numpy as np

null_vector = np.zeros((10,))
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
import numpy as np
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [16]:
import numpy as np
vector = np.arange(10,50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
import numpy as np
matrix = np.arange(9).reshape((3, 3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [19]:
import numpy as np
array = np.array([1,2,3,0,0,4,0])
indices = np.nonzero(array)
print(indices)

(array([0, 1, 2, 5], dtype=int64),)


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [20]:
import numpy as no
array = np.random.random([3,3,3])
print(array)

[[[0.81062081 0.02272083 0.94453135]
  [0.86845848 0.60101486 0.35757274]
  [0.89494946 0.14169703 0.62291385]]

 [[0.90654813 0.16062396 0.52251329]
  [0.16655717 0.60231594 0.32613233]
  [0.6509186  0.66046881 0.15003523]]

 [[0.90623128 0.94518315 0.360447  ]
  [0.25819605 0.66678087 0.24388712]
  [0.5179702  0.56909191 0.72255106]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
import numpy as np
array = np.random.random((10,10))
print("array : ")
print(array)

min_value = np.min(array)
max_value = np.max(array)

print("minimum value : ", min_value)
print("maximum value : ", max_value)

array : 
[[0.09816084 0.22178767 0.15433314 0.60570854 0.66929313 0.23891763
  0.08518513 0.50676435 0.75230628 0.83809111]
 [0.34656295 0.63487599 0.4097695  0.83922803 0.61098922 0.87315551
  0.3326302  0.45799301 0.49079245 0.87111559]
 [0.88084219 0.15306634 0.10306648 0.01916853 0.95534181 0.92074073
  0.67344025 0.17724616 0.1135042  0.85772931]
 [0.35145814 0.40427376 0.31842619 0.59316657 0.52903995 0.59543454
  0.47037951 0.93944435 0.40334451 0.961385  ]
 [0.97443897 0.23038745 0.02796458 0.12803358 0.20145028 0.86514072
  0.84519909 0.56607884 0.27099199 0.05313846]
 [0.39342634 0.31608943 0.45800444 0.17608185 0.16870405 0.54598219
  0.22392009 0.60658194 0.53998258 0.12086932]
 [0.40589617 0.02244274 0.37169651 0.59359884 0.7546175  0.76951593
  0.36086566 0.33629975 0.84809495 0.89680355]
 [0.67050844 0.80476361 0.60571368 0.46166974 0.50670884 0.60734894
  0.23561394 0.4783765  0.80986692 0.41717808]
 [0.88227816 0.25614747 0.42084899 0.88224254 0.59685154 0.70347191
  0

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [4]:
import numpy as np
vector = np.random.rand(30)
print('Vector: ')
print(vector)

mean_value = np.mean(vector)
print("Mean value:", mean_value)

Vector: 
[0.53304805 0.6681632  0.97334963 0.84581502 0.39292342 0.71140978
 0.3092908  0.58905531 0.94919142 0.00330064 0.11042911 0.87032864
 0.96001626 0.7196843  0.17892358 0.40922607 0.38234365 0.55721452
 0.50342847 0.72900038 0.71048196 0.27637338 0.37541393 0.55653447
 0.03447063 0.24585346 0.78995812 0.54434963 0.10192244 0.50873225]
Mean value: 0.5180077510231186


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [5]:
import numpy as np

# Create a 5x5 array initialized with zeros
array = np.zeros((5, 5))

# Set the border elements to 1
array[0, :] = 1  # First row
array[-1, :] = 1  # Last row
array[:, 0] = 1  # First column
array[:, -1] = 1  # Last column

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [7]:
import numpy as np

# Create a 5x5 array initialized with zeros
array = np.zeros((5, 5))

# Set the border elements to 1
array[0, :] = 1  # First row
array[-1, :] = 1  # Last row
array[:, 0] = 1  # First column
array[:, -1] = 1  # Last column

# Add border filled with zeros
border_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(border_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan:

Result: nan (Not a Number)
Explanation: Any operation involving nan (Not a Number) results in nan.
np.nan == np.nan:

Result: False
Explanation: Comparing np.nan with itself or any other value using the equality operator (==) always results in False. This is because np.nan represents an undefined or missing value.
np.inf > np.nan:

Result: False
Explanation: Comparing np.inf (infinity) with np.nan using the greater than operator (>) always results in False. np.nan represents an undefined or missing value, and it is not comparable to any other value, including infinity.
np.nan - np.nan:

Result: nan
Explanation: Subtracting np.nan from np.nan or performing any arithmetic operation involving nan results in nan.
np.nan in set([np.nan]):

Result: True
Explanation: The in operator checks whether a value is present in a given set or list. In this case, np.nan is present in the set [np.nan], so the result is True.
0.3 == 3 * 0.1:

Result: False
Explanation: Due to floating-point precision, the multiplication of 3 * 0.1 does not result in exactly 0.3. Therefore, the comparison 0.3 == 3 * 0.1 evaluates to False. It is recommended to use caution when comparing floating-point numbers for equality.





#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [8]:
import numpy as np

matrix = np.zeros((5, 5))
values = np.array([1, 2, 3, 4])

np.fill_diagonal(matrix[1:], values)

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [9]:
#To determine the index (x, y, z) of the 100th element in a (6, 7, 8) shaped array, you can use NumPy's unravel_index() function. Here's an example:


import numpy as np

shape = (6, 7, 8)
total_elements = np.prod(shape)  # Compute the total number of elements
index_100 = 99  # Zero-based index of the 100th element

indices = np.unravel_index(index_100, shape)
x, y, z = indices

print("Index (x, y, z) of the 100th element:", indices)

Index (x, y, z) of the 100th element: (1, 5, 3)


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [10]:
import numpy as np

# Create a 5x5 random matrix
matrix = np.random.random((5, 5))
print("Original matrix:")
print(matrix)

# Normalize the matrix
normalized_matrix = np.linalg.norm(matrix)
normalized_matrix = matrix / normalized_matrix

print("Normalized matrix:")
print(normalized_matrix)

Original matrix:
[[0.21294372 0.32735342 0.06414757 0.26715291 0.00900293]
 [0.38217242 0.3302126  0.41788531 0.60997579 0.82108344]
 [0.65330522 0.75015931 0.43128525 0.58562625 0.40019101]
 [0.27891085 0.5252661  0.09674245 0.3316868  0.51003733]
 [0.42806817 0.11752177 0.94369766 0.0397195  0.63688359]]
Normalized matrix:
[[0.08989901 0.13819966 0.02708135 0.11278465 0.00380079]
 [0.16134274 0.13940673 0.17641975 0.2575151  0.34663897]
 [0.2758076  0.31669675 0.18207684 0.24723539 0.1689497 ]
 [0.11774853 0.22175298 0.04084201 0.14002909 0.21532381]
 [0.18071867 0.04961448 0.39840334 0.01676849 0.26887483]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [11]:
import numpy as np

# Create a 1D array
array = np.array([1, 5, 7, 4, 9, 2, 6, 3, 8])

# Negate elements between 3 and 8
array[(array > 3) & (array < 8)] *= -1

print(array)

[ 1 -5 -7 -4  9  2 -6  3  8]


#### 18. How to round away from zero a float array ? (★☆☆)

In [12]:
import numpy as np

# Create a float array
array = np.array([-2.3, 1.5, 3.8, -4.1, 5.7])

# Round away from zero
rounded_array = np.ceil(array)

print(rounded_array)

[-2.  2.  4. -4.  6.]


#### 19. Find common values between two arrays? (★☆☆)

In [13]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find common values
common_values = np.intersect1d(array1, array2)

print(common_values)

[4 5]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#no it is false imaginary numbers need to be handled with the emath.sqrt(-1)

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [14]:
import numpy as np

# Define a generator function that generates 10 integers
def integer_generator():
    for i in range(10):
        yield i

# Use the generator function to build an array
array = np.fromiter(integer_generator(), dtype=int)

print(array)


[0 1 2 3 4 5 6 7 8 9]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [18]:
import numpy as np

vector = np.linspace(0, 124, 10, endpoint=False)

print(vector)


[  0.   12.4  24.8  37.2  49.6  62.   74.4  86.8  99.2 111.6]


#### 23. Create a random vector of size 10 and sort it (★★☆)

In [21]:
import numpy as np

# Create a random vector of size 10
vector = np.random.random(10)
print(vector)
# Sort the vector in ascending order
vector.sort()

print(vector)

[0.01791206 0.50733811 0.19511649 0.78554703 0.45849254 0.07910921
 0.55831337 0.40295616 0.14742922 0.24507142]
[0.01791206 0.07910921 0.14742922 0.19511649 0.24507142 0.40295616
 0.45849254 0.50733811 0.55831337 0.78554703]


#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [24]:
import numpy as np

# Create two random arrays A and B
A = np.random.random((3, 3))
B = np.random.random((3, 3))

# Check if A and B are equal
equal = np.array_equal(A, B)

print(equal)


False


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [25]:
import numpy as np

# Create a random vector of size 10
vector = np.random.random(10)

print("Original vector:")
print(vector)

# Find the index of the maximum value
max_index = np.argmax(vector)

# Replace the maximum value with 0
vector[max_index] = 0

print("Modified vector:")
print(vector)


Original vector:
[0.11829094 0.71827772 0.34191355 0.81006879 0.86383506 0.2108555
 0.52483758 0.85228155 0.42649911 0.04981494]
Modified vector:
[0.11829094 0.71827772 0.34191355 0.81006879 0.         0.2108555
 0.52483758 0.85228155 0.42649911 0.04981494]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [33]:
import numpy as np

# Create a vector
vector = np.array([2, 5, 7, 10, 13, 15])

# Generate a random element
random_element = np.random.choice(vector)

print("Random element:", random_element)

# Calculate absolute differences
differences = np.abs(vector - random_element)

# Find the index of the closest value
closest_index = np.argmin(differences)

# Get the closest value
closest_value = vector[closest_index]

print("Closest value:", closest_value)


Random element: 10
Closest value: 10


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [34]:
import numpy as np

# Create a float array of 32 bits
float_array = np.array([1.5, 2.7, 3.9, 4.2], dtype=np.float32)

print("Original float array:")
print(float_array)

# Convert float array to integer array in-place
float_array = float_array.astype(np.int32)

print("Converted integer array:")
print(float_array)

Original float array:
[1.5 2.7 3.9 4.2]
Converted integer array:
[1 2 3 4]


#### 28. Sort an array by the nth column? (★★☆)

In [35]:
import numpy as np

# Create a sample array
array = np.array([[4, 5, 1],
                  [2, 6, 3],
                  [8, 1, 9]])

# Specify the column number (n) to sort by
n = 1

# Get the indices that would sort the array based on the nth column
sorted_indices = np.argsort(array[:, n])

# Sort the array based on the nth column
sorted_array = array[sorted_indices]

print(sorted_array)

[[8 1 9]
 [4 5 1]
 [2 6 3]]


#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [36]:
import numpy as np

# Create a sample 2D array with null columns
array = np.array([[1, 2, np.nan, 4],
                  [5, 6, np.nan, 8],
                  [9, 10, np.nan, 12]])

# Check if any column is null
null_columns = np.any(np.isnan(array), axis=0)

if np.any(null_columns):
    print("The array has null columns.")
    print("Indices of null columns:", np.where(null_columns)[0])
else:
    print("The array does not have null columns.")


The array has null columns.
Indices of null columns: [2]


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [40]:
import numpy as np

# Original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Number of zeros to insert between each value
num_zeros = 3

# Repeat each value in the original vector
repeated_vector = np.repeat(original_vector, num_zeros + 1)

# Insert zeros between each value
new_vector = np.insert(repeated_vector, np.arange(1, len(original_vector) * (num_zeros + 1) + 1, num_zeros + 1), 0)

print(new_vector)



[1 0 1 1 1 2 0 2 2 2 3 0 3 3 3 4 0 4 4 4 5 0 5 5 5]


#### 31. Swap two rows of an array? (★★★)

In [41]:
import numpy as np

# Create a sample 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows
array[0], array[1] = array[1], array[0]

print(array)

[[4 5 6]
 [4 5 6]
 [7 8 9]]


#### 32. How to negate a boolean value inside an array? (★★★)

In [43]:
import numpy as np

# Create a sample array with boolean values
array = np.array([True, False, True, False])

# Index of the boolean value to negate
index = 2

# Negate the boolean value at the specified index
array[index] = np.logical_not(array[index])

print(array)


[ True False False False]


#### 33. Find the most frequent value in an array?

In [44]:
import numpy as np

# Create a sample array
array = np.array([1, 2, 3, 4, 2, 3, 1, 2, 2, 3])

# Find the most frequent value
most_frequent_value = np.bincount(array).argmax()

print(most_frequent_value)


2


#### 34. Get the n largest values of an array (★★★)

In [45]:
import numpy as np

# Create a sample array
array = np.array([3, 1, 7, 2, 9, 5, 6, 8, 4])

# Number of largest values to retrieve
n = 3

# Get the n largest values
largest_values = np.partition(array, -n)[-n:]

print(largest_values)


[7 8 9]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [46]:
import numpy as np

# Create a sample 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9]])

# Extract unique rows
unique_rows = np.unique(array, axis=0)

print(unique_rows)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
